version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - cagatayldzz
    labels:
      - dependencies
    versioning-strategy: increase
    rebase-strategy: disabled
