[build]
command = "npm run build && npm run export"
publish = "out"

[[redirects]]
from = "/countries"
to = "/countries.html"
status = 200
force = true

[[redirects]]
from = "/countries/*"
to = "/countries/[id].html"
status = 200
force = true
